version: '3.4'

services:
  musictracksdb:
    container_name: musictracksdb
    restart: always
    ports:
        - "27017:27017"
    volumes:
        - mongo_data:/data/db
  musicapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://musictracksdb:27017"
    depends_on:
      - musictracksdb
    ports:
      - "80"
